# Generated by Django 5.2.17 on 2026-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
